// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:arrowLeftCircle': typeof import('~icons/bi/arrow-left-circle')['default']
    'IconBi:arrowUpCircle': typeof import('~icons/bi/arrow-up-circle')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:appsCircle': typeof import('~icons/clarity/apps-circle')['default']
    'IconClarity:homeCircle': typeof import('~icons/clarity/home-circle')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:account': typeof import('~icons/mdi/account')['default']
    'IconMdi:arrowDown': typeof import('~icons/mdi/arrow-down')['default']
    'IconMdi:arrowDownCircle': typeof import('~icons/mdi/arrow-down-circle')['default']
    'IconMdi:arrowLeftCircle': typeof import('~icons/mdi/arrow-left-circle')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:logout': typeof import('~icons/mdi/logout')['default']
    'IconMdi:power': typeof import('~icons/mdi/power')['default']
    'IconMdi:settings': typeof import('~icons/mdi/settings')['default']
    'IconMdi:signout': typeof import('~icons/mdi/signout')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:cog': typeof import('~icons/uil/cog')['default']
    'IconUil:computer': typeof import('~icons/uil/computer')['default']
    'IconUil:document': typeof import('~icons/uil/document')['default']
    'IconUil:home': typeof import('~icons/uil/home')['default']
    'IconUil:info': typeof import('~icons/uil/info')['default']
    'IconUil:machine': typeof import('~icons/uil/machine')['default']
    'IconUil:money': typeof import('~icons/uil/money')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:overview': typeof import('~icons/uil/overview')['default']
    'IconUil:settings': typeof import('~icons/uil/settings')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    'IconUil:wallet': typeof import('~icons/uil/wallet')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
