# fly.toml app configuration file generated for drop-front on 2023-06-15T16:09:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "drop-front"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
